// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6Dp0eZMhSQYow4KbW89GCH8jwwHiQQeU',
    appId: '1:555333699815:web:329211a857f94b2c583a42',
    messagingSenderId: '555333699815',
    projectId: 'safespace-c7f10',
    authDomain: 'safespace-c7f10.firebaseapp.com',
    storageBucket: 'safespace-c7f10.firebasestorage.app',
    measurementId: 'G-MLHD7DZX5G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWew_BpuMD9xUdgc_VnpNEc8H8xmhSkBQ',
    appId: '1:555333699815:android:a5c69127f0ec8357583a42',
    messagingSenderId: '555333699815',
    projectId: 'safespace-c7f10',
    storageBucket: 'safespace-c7f10.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnhA22j-5bT72xIc_SAKb34cOsmWvbZKs',
    appId: '1:555333699815:ios:6cda561047aa3c76583a42',
    messagingSenderId: '555333699815',
    projectId: 'safespace-c7f10',
    storageBucket: 'safespace-c7f10.firebasestorage.app',
    iosBundleId: 'com.example.safespace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnhA22j-5bT72xIc_SAKb34cOsmWvbZKs',
    appId: '1:555333699815:ios:6cda561047aa3c76583a42',
    messagingSenderId: '555333699815',
    projectId: 'safespace-c7f10',
    storageBucket: 'safespace-c7f10.firebasestorage.app',
    iosBundleId: 'com.example.safespace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6Dp0eZMhSQYow4KbW89GCH8jwwHiQQeU',
    appId: '1:555333699815:web:e8ad7e93d4d3ca75583a42',
    messagingSenderId: '555333699815',
    projectId: 'safespace-c7f10',
    authDomain: 'safespace-c7f10.firebaseapp.com',
    storageBucket: 'safespace-c7f10.firebasestorage.app',
    measurementId: 'G-W406GNT9EY',
  );

}